### PR TITLE
Fix inconsistent parameter names when running under a namespace

### LINKED ISSUE #109: [ROS2] Inconsistent parameter names for compressed transport
The compressed transport plugin declares different parameters depending on the namespace of the node.
When the node does not have a namespace specified (i.e. it operates under the root namespaces) the parameters will look like this:
```
camera.image_raw.format
camera.image_raw.jpeg_quality                                                                         
camera.image_raw.png_level
```
When the node is put under a namespace, the plugin will add a dot character to the parameter names:
```
.camera.image_raw.format
.camera.image_raw.jpeg_quality                                                                         
.camera.image_raw.png_level
```
I could publish a fix for that but I need to know which way is the intended one.

### PR DESCRIPTION
**Pull request by bjsowa**
Fixes #109

I left the incorrect parameter names and mirror their changes to the correct ones. As #183 was just merged and the transports no longer subscribe to parameter events, I decided to implement mirroring using [pre set parameter callback](https://docs.ros.org/en/rolling/Concepts/Basic/About-Parameters.html#parameter-callbacks) which was designed specifically for this use case. 

The parameter event callback for theora transport, which checked if the configuration needs to be refreshed, was replaced by `post set parameter callback`.

This can be a bit problematic to backport to `jazzy` depending on whether we are allowed to break the ABI (I don't see any [REP 2004](https://ros.org/reps/rep-2004.html) Quality declaration).

### CODE REVIEW

File: compressed_depth_image_transport/src/compressed_depth_publisher.cpp [hunk 1]
```diff
@@ -164,5 +173,54 @@ void CompressedDepthPublisher::declareParameter(
...
+      // do not emit warnings if deprecated value matches
+      if (param.get_value_message() == recommended_value.get_value_message()) {
+        continue;
+      }
+
+      RCLCPP_WARN_STREAM(logger_,
+          "parameter `" << param.get_name() << "` is deprecated; use canonical name: `" <<
+          recommended_name << "`");
+
+      parameters.push_back(rclcpp::Parameter(recommended_name, param.get_parameter_value()));
```
Comment (ijnek) [inline compressed_depth_image_transport/src/compressed_depth_publisher.cpp]: Modifying the vector while iterating can cause undefined behavior. Consider creating a separate ``std::vector<rclcpp::Parameter>`` to store the new parameters during this iteration, and inserting them to the end of ``parameter`` afterwards.

File: compressed_depth_image_transport/src/compressed_depth_publisher.cpp [hunk 2]
```diff
@@ -164,5 +173,54 @@ void CompressedDepthPublisher::declareParameter(
...
+}
+
+void CompressedDepthPublisher::preSetParametersCallback(
+  std::vector<rclcpp::Parameter> & parameters, std::string base_name)
+{
+  for (auto & param : parameters) {
+    // Check if parameter is deprecated
+    if (deprecated_parameters_.find(param.get_name()) != deprecated_parameters_.end()) {
+      // name was generated from base_name, has to succeed
+      size_t base_name_index = param.get_name().find(base_name);
```
Comment (ijnek) [inline compressed_depth_image_transport/src/compressed_depth_publisher.cpp]: Some of this logic is redundant. Could it be simplified to something like this - 

```cpp
void CompressedDepthPublisher::preSetParametersCallback(std::vector<rclcpp::Parameter> & parameters)
{
  if (node_->get_effective_namespace() != "/")
  {
    std::vector<rclcpp::Parameter> new_parameters;
    for (const auto & param : parameters) {
      const auto& param_name = param.get_name();
      // If the parameter name starts with a dot, it's deprecated.
      // Emit a warning, and also update the non-dot-prefix parameter.
      if (param_name.at(0) == '.') {
        auto non_dot_prefixed_name = param_name.substr(1);
        RCLCPP_ERROR_STREAM(logger_,
            "parameter `" << param_name << "` with leading dot character is deprecated; use: `" <<
            non_dot_prefixed_name << "` instead");
        new_parameters.push_back(
          rclcpp::Parameter(non_dot_prefixed_name, param.get_parameter_value()));
      } else {
        // Otherwise, also update the dot-prefixed parameter
        new_parameters.emplace_back("." + param_name, param.get_parameter_value());
      }
    }
    parameters.insert(parameters.end(), new_parameters.begin(), new_parameters.end());
  }
}
```

**Review by ijnek — CHANGES_REQUESTED** [review]
Thanks for the PR! I like the use of the PreSetParameters functionality. I have left some comments. I try to maintain API / ABI compatibility in a release (rolling being an exception), so you are right, I cannot backport this PR as-is, unless there is another way to make the same changes without modifying the header files, which could be a bit difficult.

File: compressed_depth_image_transport/src/compressed_depth_publisher.cpp (hunk 1 above)
Comment (bjsowa) [reply compressed_depth_image_transport/src/compressed_depth_publisher.cpp]: You're right. I got inspired by [code from demo nodes](https://github.com/ros2/demos/blob/rolling/demo_nodes_cpp/src/parameters/set_parameters_callback.cpp#L59-L67) and didn't think it through.

File: compressed_depth_image_transport/src/compressed_depth_publisher.cpp (hunk 2 above)
Comment (bjsowa) [reply compressed_depth_image_transport/src/compressed_depth_publisher.cpp]: Each transport plugin should only manage it's own parameters so I need to check whether the parameter name is in `parameters_` or `deprecated_parameters_`.

Comment (bjsowa) [reply compressed_depth_image_transport/src/compressed_depth_publisher.cpp]: Also we can assume the node is running under a namespace because otherwise we wouldn't add the callback

**Comment by bjsowa** [comment]
> I cannot backport this PR as-is, unless there is another way to make the same changes without modifying the header files, which could be a bit difficult.

I could add the logic to existing Parameter event callbacks. The only exception is `zstd_image_transport` which does not contain any parameter callbacks.

File: compressed_depth_image_transport/src/compressed_depth_publisher.cpp (hunk 2 above)
Comment (bjsowa) [reply compressed_depth_image_transport/src/compressed_depth_publisher.cpp]: I simplified the logic and made the mirroring work both ways like in your suggestion. If you'll accept it, I'll copy the same logic to other transports.

**Comment by bjsowa** [comment]
@ijnek any feedback?

**Comment by ijnek** [comment]
Sorry for the delay, the changes you applied to compressed_depth_publisher are good, please go ahead and apply them to the other files too.

One more thing - could you add a comment in parts of the code saying "Depreated for Lyrical. Remove deprecation after Lyrical release". This helps other devs remove the deprecation notices from the codebase in the future.

**Comment by bjsowa** [comment]
> Sorry for the delay, the changes you applied to compressed_depth_publisher are good, please go ahead and apply them to the other files too.
> 
> One more thing - could you add a comment in parts of the code saying "Depreated for Lyrical. Remove deprecation after Lyrical release". This helps other devs remove the deprecation notices from the codebase in the future.

done

**Review by ijnek — APPROVED** [review]

**Comment by ijnek** [comment]
Thanks for your contribution @bjsowa
